# Generated by Django 6.1 on 2026-08-10 07:27

import apps.surveys.models
import apps.surveys.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(upload_to=apps.surveys.models.survey_image_upload_path, validators=[apps.surveys.validators.validate_survey_image])),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('accuracy', models.FloatField(help_text='GPS accuracy in meters')),
                ('attributes', models.JSONField(blank=True, default=dict, validators=[apps.surveys.validators.validate_attributes])),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_deleted'], name='surveys_sur_user_id_6b7ca2_idx')],
            },
        ),
    ]
