# Generated by Django 6.1 on 2026-08-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
